title: IPsec Blog
description: Security Blog
author: IPsec
github: https://github.com/ipsec-blog
about: Security Researcher - IT Tech
disqus_shortname: ipsecblog
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-instagram
      link: "https://www.instagram.com/ipsec0/"
    - icon: fa-twitter
      link: "https://twitter.com/1ps3c"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ali-mert-u-066065198/"
    - icon: fa-github
      link: "https://github.com/ipsec-blog"

share:
  twitter_username: 1ps3c
  fb_appid: 1749788565247320

urls:
    - text: About
      url: /about/
    - text: Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://agusmakmun.github.io"
baseurl: "https://ipsec-blog.github.io/ipsec-blog.github.io/"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
